import { APPROXIMATE_LOCATION, type MapNeed } from "@/lib/needs";

/** Sample reports shown only when no database is configured. */
export const demoNeeds: MapNeed[] = [
  {
    id: "ditch-grass",
    title: "Tall grass blocking the sidewalk",
    description: "The corner is hard to see around and the sidewalk is nearly covered. A mower and trimmer should handle it.",
    category: "Mowing & brush",
    kind: "public_cleanup",
    requestType: "general",
    requiredEquipment: [],
    vehicleType: null,
    location: "5th Ave N near 14th St",
    latitude: 29.3958,
    longitude: -94.9162,
    city: "Texas City",
    status: "open",
    createdAt: "Today",
    privateLocation: null,
    approximate: false,
    action: "demo",
    offerId: null,
  },
  {
    id: "fallen-limb",
    title: "Large broken limb in the roadway",
    description: "The limb is partly in a travel lane. This should be handled by public works rather than a volunteer.",
    category: "Road hazard",
    kind: "city_hazard",
    requestType: "general",
    requiredEquipment: [],
    vehicleType: null,
    location: "Bay St near 9th Ave",
    latitude: 29.3902,
    longitude: -94.9057,
    city: "Texas City",
    status: "referred",
    createdAt: "18 min ago",
    privateLocation: null,
    approximate: false,
    action: "demo",
    offerId: null,
  },
  {
    id: "porch-help",
    title: "Help clearing a front walkway",
    description: "A community member requested help making a walkway safer before the next rain.",
    category: "Neighbor help",
    kind: "neighbor_help",
    requestType: "general",
    requiredEquipment: [],
    vehicleType: null,
    location: APPROXIMATE_LOCATION,
    latitude: 29.4,
    longitude: -94.92,
    city: "Texas City",
    status: "open",
    createdAt: "Yesterday",
    privateLocation: null,
    approximate: true,
    action: "demo",
    offerId: null,
  },
];
