export const demoNeeds = [
  {
    id: "ditch-grass",
    title: "Tall grass blocking the sidewalk",
    description: "The corner is hard to see around and the sidewalk is nearly covered. A mower and trimmer should handle it.",
    category: "Mowing & brush",
    kind: "public_cleanup",
    location: "5th Ave N near 14th St",
    latitude: 29.3958,
    longitude: -94.9162,
    city: "Texas City",
    status: "open",
    reporterName: "A neighbor",
    createdAt: "Today",
  },
  {
    id: "fallen-limb",
    title: "Large broken limb in the roadway",
    description: "The limb is partly in a travel lane. This should be handled by public works rather than a volunteer.",
    category: "Road hazard",
    kind: "city_hazard",
    location: "Bay St near 9th Ave",
    latitude: 29.3902,
    longitude: -94.9057,
    city: "Texas City",
    status: "referred",
    reporterName: "A passerby",
    createdAt: "18 min ago",
  },
  {
    id: "porch-help",
    title: "Help clearing a front walkway",
    description: "A community member requested help making a walkway safer before the next rain.",
    category: "Neighbor help",
    kind: "neighbor_help",
    location: "Exact address shared after acceptance",
    latitude: 29.3967,
    longitude: -94.9221,
    city: "Texas City",
    status: "open",
    reporterName: "Community request",
    createdAt: "Yesterday",
  },
] as const;
