"use client";
import "maplibre-gl/dist/maplibre-gl.css";
import { FormEvent, useMemo, useState } from "react";
import Map, { Marker, NavigationControl, type MapMouseEvent } from "react-map-gl/maplibre";
import { Building2, CheckCircle2, Crosshair, HeartHandshake, ListFilter, MapPin, Plus, Search, ShieldAlert, Sparkles, X } from "lucide-react";

export type MapNeed={id:string;title:string;description:string;category:string;kind:string;location:string;city:string;status:string;reporterName:string;createdAt:string;latitude:number;longitude:number};
const detail={public_cleanup:{label:"Community-ready",icon:Sparkles,className:"ready"},city_hazard:{label:"City referral",icon:Building2,className:"city"},neighbor_help:{label:"Neighbor support",icon:HeartHandshake,className:"neighbor"}};

export function MapWorkspace({initialNeeds}:{initialNeeds:MapNeed[]}){
  const [filter,setFilter]=useState("all"); const [selected,setSelected]=useState<MapNeed|null>(initialNeeds[0]??null); const [reporting,setReporting]=useState(false); const [pin,setPin]=useState({latitude:29.3958,longitude:-94.9162}); const [query,setQuery]=useState("");
  const shown=useMemo(()=>initialNeeds.filter(n=>(filter==="all"||n.kind===filter)&&(`${n.title} ${n.category} ${n.location}`.toLowerCase().includes(query.toLowerCase()))),[initialNeeds,filter,query]);
  function mapClick(event:MapMouseEvent){setPin({latitude:event.lngLat.lat,longitude:event.lngLat.lng});setReporting(true)}
  return <section className="explore" id="explore">
    <div className="explore-heading"><div><p className="eyebrow">Around Texas City</p><h2>Find a place to help</h2></div><button className="report-cta" onClick={()=>setReporting(true)}><Plus size={18}/>Pin a new need</button></div>
    <div className="workspace">
      <aside className="need-list"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search needs or streets"/></label><div className="filter-row"><ListFilter size={16}/>{[["all","All"],["public_cleanup","Community"],["city_hazard","City"],["neighbor_help","Neighbor"]].map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className="result-count">{shown.length} nearby {shown.length===1?"need":"needs"}</div><div className="results">{shown.map(need=>{const d=detail[need.kind as keyof typeof detail];const Icon=d.icon;return <button className={`result-card ${selected?.id===need.id?"selected":""}`} key={need.id} onClick={()=>setSelected(need)}><div><span className={`status ${d.className}`}><Icon size={13}/>{d.label}</span><small>{need.createdAt}</small></div><strong>{need.title}</strong><p><MapPin size={14}/>{need.location}</p></button>})}</div></aside>
      <div className="map-shell"><Map initialViewState={{longitude:-94.9162,latitude:29.3958,zoom:13.2}} mapStyle="https://tiles.openfreemap.org/styles/bright" onClick={mapClick} cursor="crosshair"><NavigationControl position="bottom-right" showCompass={false}/>{shown.map(need=><Marker key={need.id} longitude={need.longitude} latitude={need.latitude} anchor="bottom"><button aria-label={`View ${need.title}`} className={`map-pin ${need.kind} ${selected?.id===need.id?"active":""}`} onClick={e=>{e.stopPropagation();setSelected(need)}}><span/></button></Marker>)}{reporting&&<Marker longitude={pin.longitude} latitude={pin.latitude} anchor="bottom"><div className="new-pin"><MapPin/></div></Marker>}</Map><div className="map-tip"><Crosshair size={16}/>Tap anywhere to report at that spot</div>{selected&&!reporting&&<article className="map-detail"><button className="detail-close" onClick={()=>setSelected(null)} aria-label="Close details"><X size={17}/></button><span className={`status ${detail[selected.kind as keyof typeof detail].className}`}>{detail[selected.kind as keyof typeof detail].label}</span><h3>{selected.title}</h3><p>{selected.description}</p><div className="detail-location"><MapPin size={17}/>{selected.location}, {selected.city}</div><button>{selected.kind==="city_hazard"?"Follow city response":"Offer to help"}</button></article>}</div>
    </div>
    {reporting&&<ReportSheet pin={pin} setPin={setPin} close={()=>setReporting(false)}/>} 
  </section>
}

function ReportSheet({pin,setPin,close}:{pin:{latitude:number;longitude:number};setPin:(p:{latitude:number;longitude:number})=>void;close:()=>void}){
  const [state,setState]=useState<"idle"|"saving"|"saved"|"error">("idle"); const [step,setStep]=useState(1);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("saving");const form=new FormData(event.currentTarget);const res=await fetch("/api/needs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(form),...pin})});setState(res.ok?"saved":"error");if(res.ok)setTimeout(()=>window.location.reload(),900)}
  return <div className="sheet-backdrop" onMouseDown={close}><aside className="report-sheet" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="report-title"><button className="sheet-close" onClick={close}><X/></button>{state==="saved"?<div className="success"><CheckCircle2/><h2>It’s on the map.</h2><p>Thanks for paying attention to your community.</p></div>:<form onSubmit={submit}><div className="sheet-step">Step {step} of 2</div><h2 id="report-title">{step===1?"Is this the right spot?":"What needs attention?"}</h2>{step===1?<><div className="coordinate-card"><MapPin/><div><strong>Selected map location</strong><span>{pin.latitude.toFixed(5)}, {pin.longitude.toFixed(5)}</span></div></div><p className="sheet-help">Drag the coordinates if needed, or close this panel and tap a more exact point on the map.</p><div className="coordinate-fields"><label>Latitude<input type="number" step="any" value={pin.latitude} onChange={e=>setPin({...pin,latitude:Number(e.target.value)})}/></label><label>Longitude<input type="number" step="any" value={pin.longitude} onChange={e=>setPin({...pin,longitude:Number(e.target.value)})}/></label></div><button type="button" className="primary-button wide" onClick={()=>setStep(2)}>Use this location</button></>:<><label>Who should handle it?<select name="kind" required><option value="public_cleanup">Community volunteers</option><option value="city_hazard">City or trained crews</option><option value="neighbor_help">Approved neighbor support</option></select></label><label>Short title<input name="title" required minLength={5} maxLength={100} placeholder="Broken limb blocking the sidewalk"/></label><label>What should people know?<textarea name="description" required minLength={10} maxLength={1000} placeholder="Describe the size, tools needed, and any safety concerns."/></label><div className="form-row"><label>Category<input name="category" required placeholder="Tree & brush"/></label><label>City<input name="city" required defaultValue="Texas City"/></label></div><label>Location note<input name="location" required placeholder="Nearest cross street or landmark"/></label><label>Your display name<input name="reporterName" required defaultValue="A neighbor"/></label><div className="safety-note"><ShieldAlert/><span>Never enter traffic or handle power lines, hazardous materials, or suspended limbs.</span></div>{state==="error"&&<p className="form-error">We couldn’t save this yet. Please check the details.</p>}<div className="sheet-actions"><button type="button" onClick={()=>setStep(1)}>Back</button><button className="primary-button" disabled={state==="saving"}>{state==="saving"?"Adding…":"Add to the map"}</button></div></>}</form>}</aside></div>
}
